---
title: "Math/Stats 3340 Group 38 Final Project Code"
author: "Samson Mifflin, Dawei Yuan, Mackenzie Frolic-Smart"
date: "12/9/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, render = F}
library("caret")
library("MPV")
library("faraway")
library("mltools")
library(data.table)
library(MASS)
```

```{r}
# synthetic data point already added as the last row of the csv, row8129
cardata<-read.csv("C:\\Users\\sjmif\\Downloads\\cardetailsv3withsynth.csv")
attach(cardata)
summary(cardata)
```

```{r}
#remove NA's
cardata<-cardata[complete.cases(cardata),]
anyNA(cardata)
```

```{r}
#first column should now just be year.
cardata<-data.frame(cardata[,-1])
cardata[(1:5),1]
```

```{r}
#switch to car age
cardata$car_age<-with(cardata,2020-cardata$year)
#prune year column
cardata<-data.frame(cardata[,-1])
```

```{r}
#cleaning columns with symbols
cardata$max_power<-{as.numeric(gsub("[a-zA-Z/]", "",cardata$max_power))}
cardata$engine<-{as.numeric(gsub("[a-zA-Z/]", "",cardata$engine))}
cardata$mileage<-{as.numeric(gsub("[a-zA-Z]", "",cardata$mileage))}
#the rows with CNG and LPG fuel are also removed by the previous line
```

```{r}
cardata<-cardata[complete.cases(cardata),]
anyNA(cardata)
```

```{r}
#taking out torque column
cardata<-data.frame(cardata[,-10])
```

```{r}

#visualizing the data
#table(cardata$car_age)
boxplot(cardata$car_age)
barplot(table(cardata$car_age),
main="Bar Chart of Years",
xlab="Year",
ylab="Count",
border="red",
col="blue",
density=10
)

boxplot(cardata$selling_price,main="Selling Price boxplot")
hist (cardata$selling_price, breaks=30, col="violet", xlab="Selling Price", main="Selling Price histogram")
boxplot(log(cardata$selling_price))       
        
boxplot(cardata$km_driven)
hist (cardata$km_driven, breaks=30, col="violet", xlab="Selling Price", main="km driven histogram")
boxplot(log(cardata$km_driven)) 

table(cardata$fuel)
barplot(table(cardata$fuel),
main="Bar Chart of Fuel",
xlab="Fuel",
ylab="Count",
border="red",
col="blue",
density=10
)

barplot(table(cardata$seller_type),
main="Bar Chart of Seller Type",
xlab="Fuel",
ylab="Count",
border="red",
col="blue",
density=10
)
       


barplot(table(cardata$transmission),
main="Bar Chart of Transmission",
xlab="Fuel",
ylab="Count",
border="red",
col="blue",
density=10
)

barplot(table(cardata$owner),
main="Bar Chart of Owner",
xlab="Fuel",
ylab="Count",
border="red",
col="blue",
density=10
)
       
boxplot(cardata$mileage)
hist (cardata$mileage, breaks=15, col="violet", xlab="Selling Price", main="Selling Price histogram")
       
barplot(table(cardata$seats),
main="Bar Chart of Seats",
xlab="Fuel",
ylab="Count",
border="red",
col="blue",
density=10
)
   

barplot(table(cardata$max_power),
main="Bar Chart of Max Power",
xlab="Fuel",
ylab="Count",
border="red",
col="blue",
density=10
)

boxplot(cardata$max_power, center= TRUE, scale=TRUE,main="max power boxplot")

# make correlation matrix
cormat <- round(cor(cardata[c(1,2,7,8,9,10,11)]),4)
head(cormat)
```

```{r}
#remove rows where mileage is 0
cardata<-cardata[!(cardata$mileage<0.001),]
```

```{r}
#checking the data before getting logs
summary(cardata)
cardata$selling_price <- log(cardata$selling_price)
cardata$km_driven <- log(cardata$km_driven)
cardata$max_power <- log(cardata$max_power)
#checking the data after getting logs
summary(cardata)
```

```{r}
# scale carData
scaledData <- cardata
scaledData[c(1,2,7,8,9,10,11)] <- lapply(scaledData[c(1,2,7,8,9,10,11)], function(x) c(scale(x)))
#checking the data after unit normal scaling
summary(scaledData)
```

```{r}
boxplot(scaledData$max_power, center= TRUE, scale=TRUE,main="log(max power) boxplot")
boxplot(scaledData$selling_price, center= TRUE, scale=TRUE,main="log(selling price) boxplot")
boxplot(scaledData$km_driven, center= TRUE, scale=TRUE,main="log(km driven) boxplot")
```

```{r}
#test train split
set.seed(13)
n=ceiling(0.8*length(scaledData$selling_price))
train.sample=sample(c(1:length(scaledData$selling_price)),n)
train.sample=sort(train.sample)
train_data<- scaledData[train.sample, ]
test_data <- scaledData[-train.sample, ]
```

```{r}
#MODEL SELECTION
#define model with all predictors
fullModelscaledData<-lm(selling_price ~ .,data = train_data)
```

```{r}
#stepwise bidirectional variable selection
print('VARIABLE SELECTION STEPWISE')
step.model.scaledData<-stepAIC(fullModelscaledData,direction = "both", trace = F)
summary(step.model.scaledData)
select.mod.scaledData<-step(fullModelscaledData)
print('VIFs')
vif(select.mod.scaledData)
print('Condition Number')
kappa(select.mod.scaledData)
print('Confidence Interval of Coefficients')
confint(select.mod.scaledData)
```

```{r}
plot(select.mod.scaledData, which=1, col=c("blue")) # Residuals vs Fitted Plot
plot(select.mod.scaledData, which=2, col=c("red"))  # Q-Q Plot
plot(select.mod.scaledData, which=3, col=c("blue"))  # Scale-Location Plot
plot(select.mod.scaledData, which=5, col=c("blue"))  # Residuals vs Leverage
```

```{r}
cooksd <- cooks.distance(select.mod.scaledData)
print('the largest cooks distance is')
max(cooksd)
print('the average cooks distance is')
mean(cooksd)

# Plot the Cook's Distance using the traditional 4/n criterion
plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 4/nrow(train_data), col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>4/nrow(train_data), names(cooksd),""), col="red")  # add labels
```

```{r}
# compare the selected model and the model where we remove engine
print('Comparing the selected model and the model with engine removed')
noEngineModel <- lm(formula = selling_price ~ km_driven + fuel + seller_type + transmission + owner + mileage + max_power + seats + car_age, data = train_data)
summary(noEngineModel)
vif(noEngineModel)
kappa(noEngineModel)
#test whther coefficient of quadratic and interaction terms are significant
anova(noEngineModel,select.mod.scaledData) # List the least complex model first
```

```{r}
train_data[6243,]
# remove the outlier
print('Removing the synthetic data point')
#full model
model.outlier8129removed <- lm(formula = selling_price ~ km_driven + fuel + seller_type + transmission + owner + mileage + engine + max_power + seats + car_age, data = train_data,subset=1:6242)
summary(model.outlier8129removed)
vif(model.outlier8129removed)
kappa(model.outlier8129removed)
plot(model.outlier8129removed, which=1, col=c("blue")) # Residuals vs Fitted Plot
plot(model.outlier8129removed, which=2, col=c("red"))  # Q-Q Plot
plot(model.outlier8129removed, which=3, col=c("blue"))  # Scale-Location Plot
plot(model.outlier8129removed, which=5, col=c("blue"))  # Residuals vs Leverage
```

```{r}
#stepwise bidirectional variable selection
print('VARIABLE SELECTION STEPWISE')
step.model.outlier8129removed<-stepAIC(model.outlier8129removed,direction = "both", trace = F)
summary(step.model.outlier8129removed)
select.mod.outlier8129removed<-step(step.model.outlier8129removed)
print('VIFs')
vif(step.model.outlier8129removed)
print('Condition Number')
kappa(step.model.outlier8129removed)
print('Confidence Interval of Coefficients')
confint(select.mod.scaledData)
```


```{r}
noEngineModel.outlier8129removed <- lm(formula = selling_price ~ km_driven + fuel + seller_type + transmission + owner + mileage + max_power + seats + car_age, data = train_data,subset=1:6242)
summary(noEngineModel.outlier8129removed)
vif(noEngineModel.outlier8129removed)
kappa(noEngineModel.outlier8129removed)
#test whether the adding the engine predictor is significant when compared to the no engine model
anova(noEngineModel.outlier8129removed,step.model.outlier8129removed) # List the least complex model first
```

```{r}
Noenginepreds<-predict(noEngineModel.outlier8129removed,test_data)
fullmodelpreds<-predict(model.outlier8129removed,test_data)
selectmodelpreds<-predict(select.mod.outlier8129removed,test_data)
```

```{r}
plot(test_data$selling_price,Noenginepreds,abline(c(0,1)), xlab = "actual", ylab = "predicted")
plot(test_data$selling_price,fullmodelpreds,abline(c(0,1)), xlab = "actual", ylab = "predicted")
plot(test_data$selling_price,selectmodelpreds,abline(c(0,1)), xlab = "actual", ylab = "predicted")
RMSE1<-sqrt(sum((Noenginepreds-test_data$selling_price)^2)/length(Noenginepreds))
print(RMSE1)
RMSE2<-sqrt(sum((fullmodelpreds-test_data$selling_price)^2)/length(fullmodelpreds))
print(RMSE2)
RMSE3<-sqrt(sum((selectmodelpreds-test_data$selling_price)^2)/length(selectmodelpreds))
print(RMSE3)
```